package ts.tsc.system.controller.status;

public enum ErrorStatus {
    ID_CAN_NOT_BE_SET_IN_JSON,
    NUMBER_FORMAT_EXCEPTION,
    NO_PRODUCTS_IN_STORAGE,
    ELEMENT_NOT_FOUND,
    ERROR_WHILE_SAVING,
    WRONG_DELIVERY_STATUS,
    UNKNOWN_DELIVER_STATUS,
    WRONG_NUMBER_OF_PARAMETERS,
    NOT_ENOUGH_SPACE,
    NOT_ENOUGH_PRODUCTS,
    NOT_ENOUGH_MONEY
}