package ts.tsc.system.controllers.status.enums;

public enum ErrorStatus {
    SUCCEED,
    ELEMENT_NOT_FOUND,
    ERROR_WHILE_SAVING,
    WRONG_DELIVERY_STATUS,
    UNKNOWN_DELIVER_STATUS,
    WRONG_NUMBER_OF_PARAMETERS,
    NOT_ENOUGH_SPACE,
    NOT_ENOUGH_PRODUCTS,
    CAN_NOT_BE_CANCELED,
    NOT_ENOUGH_MONEY
}